### ISSUE TITLE
firewalldがインストールされていなければこける

### ISSUE THREAD

**Issue by yusukew62** [farend/redmine-centos-ansible#3]
問題はタイトルのとおりです。
firewalldがインストールされていることを、前提条件として記載したほうがよいと思います。
# エラー内容

<pre>
TASK [system : firewalldでHTTPを許可] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "firewall-cmd --zone=public --add-service=http --permanent", "failed": true, "msg": "[Errno 2] そのようなファイルやディレクトリはありません", "rc": 2}
</pre>
# 解決策

<pre>
# yum install -y firewalld
</pre>
# 解決策後

<pre>
TASK [system : firewalldが起動しているか確認] ********************************************
ok: [localhost]
</pre>

**Comment by yusukew62** [comment]
対応ありがとうございます。クローズします。

**Comment by vividtone** [comment]
9697dd9 でfirewalldがインストールされていない場合は関係する設定を省略するよう修正しました。
