### ISSUE TITLE
CentOS 7.4: Ansibleは実行できるが、Redmineは起動しない

### ISSUE THREAD

**Issue by douhashi** [farend/redmine-centos-ansible#6]
## 事象

下記 Centos.org 公式の7系AMIからインスタンスを立ち上げて、ansibleを実行してみたところ、ansible自体は正常に終了するが、Redmineは正常動作しませんでした。

https://aws.amazon.com/marketplace/pp/B00O7WM7QW

playbookは現時点(2018/02/19)時点でのmasterブランチを利用しています。

## 手順

READMEの手順以外で叩いたコマンドとしては、一番最初に `yum update -y`しています。

## 調査

少し深追いしてみた結果は以下の通りです。

### passenger-status が参照できない

これは、systemctl の httpd.service が PrivateTmp trueになっているせいかなと思います。
参考: https://qiita.com/ayweak/items/decd9812c73e945c6b7b

それにしても、PrivateTmp falseにした状態でもpassenger-statusはエラーになりました。

### apacheエラーログ

/var/log/httpd/error_log

```
AH01276: Cannot serve directory /var/lib/redmine/public/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive
```

### 仮説: autoindexが悪さしてる？ 

外してみましたがダメでした。全体的にnot foundになります。

その後もAllowOverrideとか色々頑張ってみましたが、どうにもうまくいけませんでしたのでissueとして挙げさせていただきます。

**Comment by vividtone** [comment]
Passenger 5.2.0の場合、Railsアプリケーションをサブディレクトリにデプロイするとエラーになるようです。

```
[Wed Feb 21 07:33:03.933352 2018] [lbmethod_heartbeat:notice] [pid 52366] AH02282: No slotmem from mod_heartmonitor
[Wed Feb 21 07:33:03.933583 2018] [passenger:error] [pid 52366] *** Passenger could not be initialized because of this error: Null Value Passed to Value Constructor
```

バージョン指定で 5.1.12 をインストールするようにして回避しました (6349ce0)。Passenger 5.2.1がリリースされたら問題が修正されているか確認します。

関連: https://github.com/phusion/passenger/issues/2029

**Comment by ishikawa999** [comment]
時間が経っているため一旦Closeします。  
もしこの問題に関連して進展があれば、Reopenしてください。
